# Generated by Django 5.0.7 on 2024-09-06 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0003_todomodel_duedate_todomodel_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="dueDate",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
