# Generated by Django 5.0.7 on 2024-09-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0005_alter_todomodel_taskstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="taskStatus",
            field=models.CharField(max_length=30),
        ),
    ]
