# Generated by Django 5.0.7 on 2024-09-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0006_alter_todomodel_taskstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="taskStatus",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
